definitions:
  models.Approval:
    properties:
      approver:
        $ref: '#/definitions/models.User'
      approver_id:
        type: integer
      created_at:
        type: string
      expense_id:
        type: integer
      id:
        type: integer
      notes:
        type: string
      status:
        $ref: '#/definitions/models.ExpenseStatus'
    type: object
  models.Expense:
    properties:
      amount:
        type: integer
      approvals:
        items:
          $ref: '#/definitions/models.Approval'
        type: array
      auto_approved:
        type: boolean
      description:
        type: string
      external_id:
        type: string
      id:
        type: integer
      processed_at:
        type: string
      receipt_url:
        type: string
      requires_approval:
        type: boolean
      status:
        $ref: '#/definitions/models.ExpenseStatus'
      submitted_at:
        type: string
      user_id:
        type: integer
    type: object
  models.ExpenseListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Expense'
        type: array
      meta:
        $ref: '#/definitions/models.ExpensePaginationMeta'
    type: object
  models.ExpensePaginationMeta:
    properties:
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.ExpenseStatus:
    enum:
    - pending
    - approved
    - rejected
    - auto_approved
    - completed
    type: string
    x-enum-varnames:
    - StatusPending
    - StatusApproved
    - StatusRejected
    - StatusAutoApproved
    - StatusCompleted
  models.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  models.LoginResponse:
    properties:
      role:
        type: string
      token:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      role:
        description: employee, manager
        type: string
    type: object
info:
  contact: {}
  description: API untuk tugas teknis Mekari.
  title: Expense Management API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: 'Login untuk mendapatkan token. Gunakan email: employee@mekari.com
        atau manager@mekari.com'
      parameters:
      - description: Credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User Login
      tags:
      - auth
  /api/expenses:
    get:
      description: Mengambil daftar pengeluaran. Filter otomatis berdasarkan role
        user.
      parameters:
      - description: Filter status (pending, approved, rejected)
        in: query
        name: status
        type: string
      - default: 10
        description: Limit data per halaman
        in: query
        name: limit
        type: integer
      - default: 1
        description: Nomor halaman
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ExpenseListResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get list of expenses
      tags:
      - expenses
    post:
      consumes:
      - application/json
      description: Submit pengeluaran baru oleh employee
      parameters:
      - description: Expense object
        in: body
        name: expense
        required: true
        schema:
          $ref: '#/definitions/models.Expense'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Expense'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
      security:
      - BearerAuth: []
      summary: Submit a new expense
      tags:
      - expenses
  /api/expenses/{id}:
    get:
      description: Mendapatkan detail pengeluaran berdasarkan ID
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Expense'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
      security:
      - BearerAuth: []
      summary: Get expense detail
      tags:
      - expenses
  /api/expenses/{id}/approve:
    put:
      description: Menyetujui pengeluaran (Hanya untuk Manager)
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
      security:
      - BearerAuth: []
      summary: Approve an expense
      tags:
      - expenses
  /api/expenses/{id}/reject:
    put:
      description: Menolak pengeluaran (Hanya untuk Manager)
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
      security:
      - BearerAuth: []
      summary: Reject an expense
      tags:
      - expenses
securityDefinitions:
  BearerAuth:
    description: 'Masukkan token dengan format: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
